###################
# STAGE 1: builder
###################

# Build currently doesn't work on > Java 11 (i18n utils are busted) so build on 8 until we fix this
FROM adoptopenjdk/openjdk8:centos as builder

WORKDIR /app/source

ENV FC_LANG en-US
ENV LC_CTYPE en_US.UTF-8

# bash:    various shell scripts
# wget:    installing lein
# git:     ./bin/version
# make:    backend building
# gettext: translations
RUN yum install -y coreutils bash git wget make gettext

# lein:    backend dependencies and building
ADD ./bin/lein /usr/local/bin/lein
RUN chmod 744 /usr/local/bin/lein
RUN lein upgrade

# install dependencies before adding the rest of the source to maximize caching

# backend dependencies
ADD project.clj .
RUN lein deps

# add the rest of the source
ADD . .

# build the app
RUN bin/build

# install updated cacerts to /etc/ssl/certs/java/cacerts
# RUN yum install -y java-cacerts

# ###################
# # STAGE 2: runner
# ###################

FROM adoptopenjdk/openjdk11:centos-jre as runner

ARG CONDA_VERSION="4.7.12.1"
ARG CONDA_MD5="81c773ff87af5cfac79ab862942ab6b3"
ARG CONDA_DIR="/opt/conda"
ENV PATH="$CONDA_DIR/bin:$PATH"
ENV PYTHONDONTWRITEBYTECODE=1

# Install conda
COPY condarc /root/.condarc
RUN echo "**** install dev packages ****" && \
  yum install -y bash ca-certificates wget && \
  \
  echo "**** get Miniconda ****" && \
  mkdir -p "$CONDA_DIR" && \
  wget "https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh" -O miniconda.sh && \
  echo "$CONDA_MD5  miniconda.sh" | md5sum -c && \
  \
  echo "**** install Miniconda ****" && \
  bash miniconda.sh -f -b -p "$CONDA_DIR" && \
  echo "export PATH=$PATH:$CONDA_DIR/bin" > /etc/profile.d/conda.sh && \
  \
  echo "**** setup Miniconda ****" && \
  conda update --all --yes && \
  conda config --set auto_update_conda False && \
  \
  echo "Initialize conda" && \
  conda init bash && \
  echo "**** cleanup ****" && \
  rm -f miniconda.sh && \
  conda clean --all --force-pkgs-dirs --yes && \
  find "$CONDA_DIR" -follow -type f \( -iname '*.a' -o -iname '*.pyc' -o -iname '*.js.map' \) -delete && \
  \
  echo "**** finalize ****" && \
  mkdir -p "$CONDA_DIR/locks" && \
  chmod 777 "$CONDA_DIR/locks"

# Add Nvidia Runtime
RUN distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && \
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | tee /etc/yum.repos.d/nvidia-docker.repo
RUN yum install nvidia-container-toolkit -y

WORKDIR /app

ENV FC_LANG en-US
ENV LC_CTYPE en_US.UTF-8

# Dependencies
## zip for zipping dependencies of workflow
# gcc, libc-dev, libxml2 and libxml2-dev for r packages
RUN yum install -y bash ttf-dejavu fontconfig libgxps gcc libc-dev libxml2 libxml2-dev automake git unzip xorg epel-release

# Install R-base for tservice plugins
RUN conda install r-base=3.6.3

# Install Python Environment
RUN pip3 install poetry

# Add Matlab Runtime
RUN mkdir /mcr-install && \
    mkdir /opt/mcr && \
    cd /mcr-install && \
    wget --no-check-certificate -q https://ssd.mathworks.com/supportfiles/downloads/R2020a/Release/6/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2020a_Update_6_glnxa64.zip && \
    unzip -q MATLAB_Runtime_R2020a_Update_6_glnxa64.zip && \
    rm -f MATLAB_Runtime_R2020a_Update_6_glnxa64.zip && \
    ./install -destinationFolder /opt/mcr -agreeToLicense yes -mode silent && \
    cd / && \
    rm -rf mcr-install    

# Configure environment variables for MCR
ENV LD_LIBRARY_PATH /usr/local/lib:/usr/local/lib64:/usr/lib64:/lib64:/opt/mcr/v98/runtime/glnxa64:/opt/mcr/v98/bin/glnxa64:/opt/mcr/v98/sys/os/glnxa64:/opt/mcr/v98/extern/bin/glnxa64

ENV XAPPLRESDIR /etc/X11/app-defaults

# Add Openslide
RUN yum install openslide -y

# Add tservice script and uberjar
RUN mkdir -p bin target/uberjar
COPY --from=builder /app/source/target/uberjar/tservice.jar /app/target/uberjar/
COPY --from=builder /app/source/bin /app/bin

# Expose our default runtime port
EXPOSE 3000

# Run it
ENTRYPOINT ["/app/bin/start"]